check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.1 "DLSCH encoding time" "< 230")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.1 "DLSCH encoding time" "< 100")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.2 "DLSCH encoding time" "< 300")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.2 "DLSCH encoding time" "< 100")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.3 "DLSCH encoding time" "< 350")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.3 "DLSCH encoding time" "< 200")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.4 "DLSCH encoding time" "< 300")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.4 "DLSCH encoding time" "< 150")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.5 "DLSCH encoding time" "< 350")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.5 "DLSCH encoding time" "< 250")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.6 "DLSCH encoding time" "< 400")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.6 "DLSCH encoding time" "< 400")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.7 "DLSCH encoding time" "< 400")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.7 "DLSCH encoding time" "< 200")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.8 "DLSCH encoding time" "< 450")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.8 "DLSCH encoding time" "< 500")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.9 "DLSCH encoding time" "< 500")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.9 "DLSCH encoding time" "< 500")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.10 "DLSCH encoding time" "< 400")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.10 "DLSCH encoding time" "< 200")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.11 "DLSCH encoding time" "< 400")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.11 "DLSCH encoding time" "< 300")
check_physim_threshold(physim.5g-offload.nr_dlsim.testCPU.12 "DLSCH encoding time" "< 450")
check_physim_threshold(physim.5g-offload.nr_dlsim.testT2.12 "DLSCH encoding time" "< 450")

check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.13 "ULSCH total decoding time" "< 300")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.13 "ULSCH total decoding time" "< 100")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.14 "ULSCH total decoding time" "< 300")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.14 "ULSCH total decoding time" "< 150")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.15 "ULSCH total decoding time" "< 250")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.15 "ULSCH total decoding time" "< 250")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.16 "ULSCH total decoding time" "< 300")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.16 "ULSCH total decoding time" "< 150")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.17 "ULSCH total decoding time" "< 400")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.17 "ULSCH total decoding time" "< 350")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.18 "ULSCH total decoding time" "< 400")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.18 "ULSCH total decoding time" "< 550")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.19 "ULSCH total decoding time" "< 300")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.19 "ULSCH total decoding time" "< 250")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.20 "ULSCH total decoding time" "< 600")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.20 "ULSCH total decoding time" "< 650")
check_physim_threshold(physim.5g-offload.nr_ulsim.testCPU.21 "ULSCH total decoding time" "< 650")
check_physim_threshold(physim.5g-offload.nr_ulsim.testT2.21 "ULSCH total decoding time" "< 1100")
