/*
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
 * Copyright 2022 Sequans Communications.
=======
 ******************************************************************
>>>>>>> ad6fd43160... Sequans W34 delivery preparation PART2: SIDL preparation
 *
 * Module  : ACP - Asynchronous Communication Protocol
 *
 * Purpose : THIS FILE IS AUTOMATICALLY GENERATED !
 *
<<<<<<< HEAD
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
=======
 ******************************************************************
=======
 * Copyright 2022 Sequans Communications.
>>>>>>> d0b9b399db... bug #121474 - [L3 SIMU] handshake impacted by 120788 - alignment with 5G
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
<<<<<<< HEAD
=======
>>>>>>> ad6fd43160... Sequans W34 delivery preparation PART2: SIDL preparation
 *****************************************************************
 *
 *  Copyright (c) 2014-2021 SEQUANS Communications.
 *  All rights reserved.
 *
 *  This is confidential and proprietary source code of SEQUANS
 *  Communications. The use of the present source code and all
 *  its derived forms is exclusively governed by the restricted
 *  terms and conditions set forth in the SEQUANS
 *  Communications' EARLY ADOPTER AGREEMENT and/or LICENCE
 *  AGREEMENT. The present source code and all its derived
 *  forms can ONLY and EXCLUSIVELY be used with SEQUANS
 *  Communications' products. The distribution/sale of the
 *  present source code and all its derived forms is EXCLUSIVELY
 *  RESERVED to regular LICENCE holder and otherwise STRICTLY
 *  PROHIBITED.
 *
 *****************************************************************
<<<<<<< HEAD
>>>>>>> 28371f1b82... Reabsed SRB Changes
=======
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
>>>>>>> d0b9b399db... bug #121474 - [L3 SIMU] handshake impacted by 120788 - alignment with 5G
=======
>>>>>>> ad6fd43160... Sequans W34 delivery preparation PART2: SIDL preparation
 */

#pragma once

#include "acp.h"

SIDL_BEGIN_C_INTERFACE
SIDL_END_C_INTERFACE
