/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#ifndef OAI_MEMPROF_ACTIVE_WRAP_INTERNAL_H
#define OAI_MEMPROF_ACTIVE_WRAP_INTERNAL_H

#include "oai_memprof_active_runtime_abi.h"
#include "oai_memprof_wrap_internal.h"

#include <stdbool.h>
#include <stdint.h>

#define OAI_MEMPROF_FLAG_ADDRESS_BEFORE_VALID (UINT32_C(1) << 0)
#define OAI_MEMPROF_FLAG_ADDRESS_AFTER_VALID (UINT32_C(1) << 1)
#define OAI_MEMPROF_FLAG_ARG0_VALID (UINT32_C(1) << 2)
#define OAI_MEMPROF_FLAG_ARG1_VALID (UINT32_C(1) << 3)
#define OAI_MEMPROF_FLAG_ARG2_VALID (UINT32_C(1) << 4)
#define OAI_MEMPROF_FLAG_ZERO_SIZE_REQUEST (UINT32_C(1) << 9)
#define OAI_MEMPROF_FLAG_CALLOC_PRODUCT_OVERFLOW (UINT32_C(1) << 10)
#define OAI_MEMPROF_FLAG_SUCCESSOR_CREATED (UINT32_C(1) << 11)
#define OAI_MEMPROF_FLAG_PREDECESSOR_ENDED (UINT32_C(1) << 12)
#define OAI_MEMPROF_FLAG_OPERATION_FAILED (UINT32_C(1) << 13)
#define OAI_MEMPROF_FLAG_REALLOCARRAY_PRODUCT_OVERFLOW (UINT32_C(1) << 19)
#define OAI_MEMPROF_FLAG_RESULT_ERRNO (UINT32_C(1) << 24)
#define OAI_MEMPROF_FLAG_RESULT_DIRECT_RETURN (UINT32_C(1) << 25)

#endif /* OAI_MEMPROF_ACTIVE_WRAP_INTERNAL_H */
