#ifndef RRC_RECONFIGURATION_COMPLETE_INDICATOR_F1AP
#define RRC_RECONFIGURATION_COMPLETE_INDICATOR_F1AP 

// 9.3.1.30
typedef enum{

  TRUE_RRC_RECONF_CMPLT_IND , 
  FAILURE_RRC_RECONF_CMPLT_IND ,
  END_RRC_RECONF_CMPLT_IND

} rrc_reconf_cmplt_ind_e;

#endif

