/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "common/utils/memprof/oai_memprof_wire.h"

#include <limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CHECK(condition)                                                              \
  do {                                                                                \
    if (!(condition)) {                                                               \
      fprintf(stderr, "CHECK failed at %s:%d: %s\n", __FILE__, __LINE__, #condition); \
      return false;                                                                   \
    }                                                                                 \
  } while (0)

_Static_assert(OAI_MEMPROF_EVENT_V1_WIRE_SIZE == 96, "schema-v1 event size changed");

/*
 * This vector is written as literal wire bytes. It is deliberately not
 * generated by the codec under test.
 */
static const uint8_t literal_event_v1[OAI_MEMPROF_EVENT_V1_WIRE_SIZE] = {
    0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, /* thread_sequence */
    0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12, 0x11, /* counter_enter */
    0x28, 0x27, 0x26, 0x25, 0x24, 0x23, 0x22, 0x21, /* counter_exit */
    0x38, 0x37, 0x36, 0x35, 0x34, 0x33, 0x32, 0x31, /* address_before */
    0x48, 0x47, 0x46, 0x45, 0x44, 0x43, 0x42, 0x41, /* address_after */
    0x58, 0x57, 0x56, 0x55, 0x54, 0x53, 0x52, 0x51, /* arg0 */
    0x68, 0x67, 0x66, 0x65, 0x64, 0x63, 0x62, 0x61, /* arg1 */
    0x78, 0x77, 0x76, 0x75, 0x74, 0x73, 0x72, 0x71, /* arg2 */
    0x84, 0x83, 0x82, 0x81, /* context_id */
    0x94, 0x93, 0x92, 0x91, /* callsite_id */
    0xa4, 0xa3, 0xa2, 0xa1, /* thread_index */
    0xb4, 0xb3, 0xb2, 0xb1, /* flags */
    0x88, 0xa9, 0xcb, 0xed, /* result_code = -0x12345678 */
    0xc2, 0xc1, /* api_id */
    0xd2, 0xd1, /* event_kind */
    0xe2, 0xe1, /* cpu_enter */
    0xf2, 0xf1, /* cpu_exit */
    0x00, 0x00, 0x00, 0x00, /* reserved_zero */
};

static oai_memprof_event_v1_t literal_host_event(void)
{
  return (oai_memprof_event_v1_t){
      .thread_sequence = UINT64_C(0x0102030405060708),
      .counter_enter = UINT64_C(0x1112131415161718),
      .counter_exit = UINT64_C(0x2122232425262728),
      .address_before = UINT64_C(0x3132333435363738),
      .address_after = UINT64_C(0x4142434445464748),
      .arg0 = UINT64_C(0x5152535455565758),
      .arg1 = UINT64_C(0x6162636465666768),
      .arg2 = UINT64_C(0x7172737475767778),
      .context_id = UINT32_C(0x81828384),
      .callsite_id = UINT32_C(0x91929394),
      .thread_index = UINT32_C(0xa1a2a3a4),
      .flags = UINT32_C(0xb1b2b3b4),
      .result_code = -INT32_C(0x12345678),
      .api_id = UINT16_C(0xc1c2),
      .event_kind = UINT16_C(0xd1d2),
      .cpu_enter = UINT16_C(0xe1e2),
      .cpu_exit = UINT16_C(0xf1f2),
  };
}

static bool host_events_equal(const oai_memprof_event_v1_t *left, const oai_memprof_event_v1_t *right)
{
  return left->thread_sequence == right->thread_sequence && left->counter_enter == right->counter_enter
         && left->counter_exit == right->counter_exit && left->address_before == right->address_before
         && left->address_after == right->address_after && left->arg0 == right->arg0 && left->arg1 == right->arg1
         && left->arg2 == right->arg2 && left->context_id == right->context_id && left->callsite_id == right->callsite_id
         && left->thread_index == right->thread_index && left->flags == right->flags && left->result_code == right->result_code
         && left->api_id == right->api_id && left->event_kind == right->event_kind && left->cpu_enter == right->cpu_enter
         && left->cpu_exit == right->cpu_exit;
}

static bool test_literal_decode(void)
{
  const oai_memprof_event_v1_t expected = literal_host_event();
  oai_memprof_event_v1_t actual = {0};

  CHECK(oai_memprof_event_v1_decode(&actual, literal_event_v1, sizeof(literal_event_v1)) == OAI_MEMPROF_WIRE_OK);
  CHECK(host_events_equal(&actual, &expected));
  return true;
}

static bool test_literal_encode(void)
{
  const oai_memprof_event_v1_t event = literal_host_event();
  uint8_t encoded[OAI_MEMPROF_EVENT_V1_WIRE_SIZE];
  memset(encoded, 0xa5, sizeof(encoded));

  CHECK(oai_memprof_event_v1_encode(&event, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(memcmp(encoded, literal_event_v1, sizeof(encoded)) == 0);
  return true;
}

static bool test_signed_i32_extremes(void)
{
  oai_memprof_event_v1_t event = literal_host_event();
  oai_memprof_event_v1_t decoded = {0};
  uint8_t encoded[OAI_MEMPROF_EVENT_V1_WIRE_SIZE];

  event.result_code = INT32_MIN;
  CHECK(oai_memprof_event_v1_encode(&event, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 0] == 0x00);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 1] == 0x00);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 2] == 0x00);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 3] == 0x80);
  CHECK(oai_memprof_event_v1_decode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(decoded.result_code == INT32_MIN);

  event.result_code = INT32_MAX;
  CHECK(oai_memprof_event_v1_encode(&event, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 0] == 0xff);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 1] == 0xff);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 2] == 0xff);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 3] == 0x7f);
  CHECK(oai_memprof_event_v1_decode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(decoded.result_code == INT32_MAX);

  event.result_code = -INT32_C(1);
  CHECK(oai_memprof_event_v1_encode(&event, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 0] == 0xff);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 1] == 0xff);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 2] == 0xff);
  CHECK(encoded[OAI_MEMPROF_EVENT_V1_RESULT_CODE_OFFSET + 3] == 0xff);
  CHECK(oai_memprof_event_v1_decode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(decoded.result_code == -INT32_C(1));
  return true;
}

static bool test_exact_size_and_null_rejection(void)
{
  const oai_memprof_event_v1_t event = literal_host_event();
  const oai_memprof_event_v1_t sentinel = {
      .thread_sequence = UINT64_MAX,
      .counter_enter = UINT64_MAX,
      .counter_exit = UINT64_MAX,
      .address_before = UINT64_MAX,
      .address_after = UINT64_MAX,
      .arg0 = UINT64_MAX,
      .arg1 = UINT64_MAX,
      .arg2 = UINT64_MAX,
      .context_id = UINT32_MAX,
      .callsite_id = UINT32_MAX,
      .thread_index = UINT32_MAX,
      .flags = UINT32_MAX,
      .result_code = INT32_MIN,
      .api_id = UINT16_MAX,
      .event_kind = UINT16_MAX,
      .cpu_enter = UINT16_MAX,
      .cpu_exit = UINT16_MAX,
  };
  oai_memprof_event_v1_t decoded = sentinel;
  uint8_t destination[OAI_MEMPROF_EVENT_V1_WIRE_SIZE + 1];
  memset(destination, 0x5a, sizeof(destination));

  CHECK(oai_memprof_event_v1_encode(NULL, destination, OAI_MEMPROF_EVENT_V1_WIRE_SIZE) == OAI_MEMPROF_WIRE_NULL_ARGUMENT);
  CHECK(oai_memprof_event_v1_encode(&event, NULL, OAI_MEMPROF_EVENT_V1_WIRE_SIZE) == OAI_MEMPROF_WIRE_NULL_ARGUMENT);
  CHECK(oai_memprof_event_v1_decode(NULL, literal_event_v1, sizeof(literal_event_v1)) == OAI_MEMPROF_WIRE_NULL_ARGUMENT);
  CHECK(oai_memprof_event_v1_decode(&decoded, NULL, sizeof(literal_event_v1)) == OAI_MEMPROF_WIRE_NULL_ARGUMENT);
  CHECK(host_events_equal(&decoded, &sentinel));

  CHECK(oai_memprof_event_v1_encode(&event, destination, OAI_MEMPROF_EVENT_V1_WIRE_SIZE - 1) == OAI_MEMPROF_WIRE_WRONG_SIZE);
  CHECK(oai_memprof_event_v1_encode(&event, destination, OAI_MEMPROF_EVENT_V1_WIRE_SIZE + 1) == OAI_MEMPROF_WIRE_WRONG_SIZE);
  CHECK(oai_memprof_event_v1_encode(&event, destination, 0) == OAI_MEMPROF_WIRE_WRONG_SIZE);
  for (size_t i = 0; i < sizeof(destination); ++i)
    CHECK(destination[i] == 0x5a);

  CHECK(oai_memprof_event_v1_decode(&decoded, literal_event_v1, OAI_MEMPROF_EVENT_V1_WIRE_SIZE - 1) == OAI_MEMPROF_WIRE_WRONG_SIZE);
  CHECK(oai_memprof_event_v1_decode(&decoded, destination, OAI_MEMPROF_EVENT_V1_WIRE_SIZE + 1) == OAI_MEMPROF_WIRE_WRONG_SIZE);
  CHECK(oai_memprof_event_v1_decode(&decoded, destination, 0) == OAI_MEMPROF_WIRE_WRONG_SIZE);
  CHECK(host_events_equal(&decoded, &sentinel));
  return true;
}

static bool test_nonzero_reserved_rejection(void)
{
  uint8_t invalid[OAI_MEMPROF_EVENT_V1_WIRE_SIZE];
  memcpy(invalid, literal_event_v1, sizeof(invalid));
  invalid[OAI_MEMPROF_EVENT_V1_RESERVED_ZERO_OFFSET + 3] = 0x80;

  const oai_memprof_event_v1_t sentinel = literal_host_event();
  oai_memprof_event_v1_t decoded = sentinel;
  decoded.thread_sequence++;
  const oai_memprof_event_v1_t unchanged = decoded;

  CHECK(oai_memprof_event_v1_decode(&decoded, invalid, sizeof(invalid)) == OAI_MEMPROF_WIRE_NONZERO_RESERVED);
  CHECK(host_events_equal(&decoded, &unchanged));
  return true;
}

static bool test_catalog_fields_are_structurally_opaque(void)
{
  oai_memprof_event_v1_t event = {
      .flags = UINT32_MAX,
      .api_id = UINT16_MAX,
      .event_kind = UINT16_MAX,
  };
  oai_memprof_event_v1_t decoded = {0};
  uint8_t encoded[OAI_MEMPROF_EVENT_V1_WIRE_SIZE];

  CHECK(oai_memprof_event_v1_encode(&event, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(oai_memprof_event_v1_decode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_WIRE_OK);
  CHECK(host_events_equal(&decoded, &event));
  return true;
}

static bool run_tests(void)
{
  return test_literal_decode() && test_literal_encode() && test_signed_i32_extremes() && test_exact_size_and_null_rejection()
         && test_nonzero_reserved_rejection() && test_catalog_fields_are_structurally_opaque();
}

static bool emit_literal_hex(void)
{
  const oai_memprof_event_v1_t event = literal_host_event();
  uint8_t encoded[OAI_MEMPROF_EVENT_V1_WIRE_SIZE];
  if (oai_memprof_event_v1_encode(&event, encoded, sizeof(encoded)) != OAI_MEMPROF_WIRE_OK)
    return false;

  for (size_t index = 0; index < sizeof(encoded); ++index)
    if (printf("%02x", (unsigned int)encoded[index]) != 2)
      return false;
  if (putchar('\n') == EOF)
    return false;
  return fflush(stdout) == 0 && !ferror(stdout);
}

int main(int argc, char **argv)
{
  const bool emit = argc == 2 && strcmp(argv[1], "--emit-literal-hex") == 0;
  if (argc != 1 && !emit) {
    fprintf(stderr, "usage: %s [--emit-literal-hex]\n", argv[0]);
    return EXIT_FAILURE;
  }

  if (!run_tests())
    return EXIT_FAILURE;

  if (emit) {
    if (!emit_literal_hex())
      return EXIT_FAILURE;
  } else {
    puts("schema-v1 event wire tests passed");
  }
  return EXIT_SUCCESS;
}
