/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include "common/utils/memprof/oai_memprof_container_wire.h"

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CHECK(condition)                                                              \
  do {                                                                                \
    if (!(condition)) {                                                               \
      fprintf(stderr, "CHECK failed at %s:%d: %s\n", __FILE__, __LINE__, #condition); \
      return false;                                                                   \
    }                                                                                 \
  } while (0)

_Static_assert(OAI_MEMPROF_CONTAINER_V1_OPENING_HEADER_SIZE == 512, "opening-header size changed");
_Static_assert(OAI_MEMPROF_CONTAINER_V1_CHUNK_HEADER_SIZE == 32, "chunk-header size changed");
_Static_assert(OAI_MEMPROF_CONTAINER_V1_TRAILER_HEADER_SIZE == 256, "trailer-header size changed");
_Static_assert(OAI_MEMPROF_CONTAINER_V1_EVENT_TOTAL_ENTRY_SIZE == 32, "event-total size changed");
_Static_assert(OAI_MEMPROF_CONTAINER_V1_DIAGNOSTIC_TOTAL_ENTRY_SIZE == 32, "diagnostic-total size changed");
_Static_assert(OAI_MEMPROF_CONTAINER_V1_OBJECT_ENTRY_SIZE == 64, "object-entry size changed");
_Static_assert(OAI_MEMPROF_CONTAINER_V1_FOOTER_SIZE == 256, "footer size changed");

/*
 * These arrays are independent literal wire bytes copied from the frozen
 * vectors. They are not generated by the codec under test.
 */
static const uint8_t literal_opening_header[OAI_MEMPROF_CONTAINER_V1_OPENING_HEADER_SIZE] = {
    0x4f, 0x41, 0x49, 0x4d, 0x45, 0x4d, 0x30, 0x31, 0x01, 0x00, 0x00, 0x00, 0x00, 0x02, 0x60, 0x00, 0x20, 0x00, 0x00, 0x00, 0x0f,
    0x00, 0x00, 0x00, 0x04, 0x03, 0x02, 0x01, 0x00, 0x10, 0x00, 0x00, 0x08, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x08, 0x07,
    0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x00, 0x18, 0x0d, 0x8f, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x88, 0x77, 0x66, 0x55,
    0x44, 0x33, 0x22, 0x11, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x00, 0x00, 0x2a, 0x36, 0xfe, 0x9c, 0x97, 0x17, 0x39,
    0x30, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x46, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd,
    0xee, 0xff, 0xff, 0xee, 0xdd, 0xcc, 0xbb, 0xaa, 0x49, 0x88, 0x87, 0x76, 0x65, 0x54, 0x43, 0x32, 0x21, 0x10, 0x01, 0x00, 0x01,
    0x00, 0x14, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x21, 0x22, 0x23, 0x24,
    0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39,
    0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e,
    0x4f, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f, 0x60, 0x61, 0x62, 0x63,
    0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78,
    0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d,
    0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b, 0x9c, 0x9d, 0x9e, 0x9f, 0xa0, 0xa1, 0xa2,
    0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7,
    0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf, 0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb, 0xcc,
    0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0xf4, 0xa3, 0x1c, 0xdf,
};

static const uint8_t literal_event_record[OAI_MEMPROF_CONTAINER_V1_EVENT_RECORD_SIZE] = {
    0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12, 0x11, 0x28, 0x27, 0x26, 0x25,
    0x24, 0x23, 0x22, 0x21, 0x38, 0x37, 0x36, 0x35, 0x34, 0x33, 0x32, 0x31, 0x48, 0x47, 0x46, 0x45, 0x44, 0x43, 0x42, 0x41,
    0x58, 0x57, 0x56, 0x55, 0x54, 0x53, 0x52, 0x51, 0x68, 0x67, 0x66, 0x65, 0x64, 0x63, 0x62, 0x61, 0x78, 0x77, 0x76, 0x75,
    0x74, 0x73, 0x72, 0x71, 0x84, 0x83, 0x82, 0x81, 0x94, 0x93, 0x92, 0x91, 0xa4, 0xa3, 0xa2, 0xa1, 0xb4, 0xb3, 0xb2, 0xb1,
    0x88, 0xa9, 0xcb, 0xed, 0xc2, 0xc1, 0xd2, 0xd1, 0xe2, 0xe1, 0xf2, 0xf1, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t literal_chunk_header[OAI_MEMPROF_CONTAINER_V1_CHUNK_HEADER_SIZE] = {
    0x4f, 0x4d, 0x43, 0x31, 0x01, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x1e, 0xcc, 0x39, 0xb6, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t literal_trailer_header[OAI_MEMPROF_CONTAINER_V1_TRAILER_HEADER_SIZE] = {
    0x4f, 0x41, 0x49, 0x5f, 0x4d, 0x45, 0x4d, 0x50, 0x52, 0x4f, 0x46, 0x5f, 0x54, 0x52, 0x31, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x80, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01,
    0x01, 0x00, 0x07, 0x00, 0x05, 0x00, 0x00, 0x00, 0x81, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x07, 0x06, 0x05,
    0x04, 0x03, 0x02, 0x01, 0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x99, 0x77, 0x66, 0x55,
    0x44, 0x33, 0x22, 0x11, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x08, 0x08, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01,
    0x00, 0x00, 0x2a, 0x36, 0xfe, 0x9c, 0x97, 0x17, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x20, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t literal_event_total[OAI_MEMPROF_CONTAINER_V1_EVENT_TOTAL_ENTRY_SIZE] = {
    0x02, 0x01, 0x04, 0x03, 0x00, 0x00, 0x00, 0x00, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t literal_diagnostic_total[OAI_MEMPROF_CONTAINER_V1_DIAGNOSTIC_TOTAL_ENTRY_SIZE] = {
    0x01, 0x00, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0x02, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t literal_object_entry[OAI_MEMPROF_CONTAINER_V1_OBJECT_ENTRY_SIZE] = {
    0x01, 0x00, 0x01, 0x00, 0x05, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f,
    0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f,
};

static const uint8_t literal_footer[OAI_MEMPROF_CONTAINER_V1_FOOTER_SIZE] = {
    0x4f, 0x41, 0x49, 0x5f, 0x4d, 0x45, 0x4d, 0x50, 0x52, 0x4f, 0x46, 0x5f, 0x45, 0x4e, 0x44, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x80, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x11, 0x12, 0x13,
    0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27,
    0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b,
    0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f,
    0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f, 0x60, 0x61, 0x62, 0x63,
    0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x27, 0x8c, 0x9d, 0x95, 0x37, 0x59, 0x1a, 0x84, 0x65, 0x93, 0xd7, 0xaa, 0xb9, 0x02, 0xd2, 0x9c,
    0xd5, 0xf8, 0x74, 0xe1, 0xc8, 0xef, 0x8a, 0x02, 0x3d, 0xf9, 0x3d, 0xaf, 0x1f, 0x11, 0x4c, 0xd1,
};

static bool bytes_are_value(const uint8_t *bytes, size_t size, uint8_t value)
{
  for (size_t index = 0; index < size; ++index)
    if (bytes[index] != value)
      return false;
  return true;
}

static bool test_crc32c(void)
{
  static const uint8_t digits[] = {'1', '2', '3', '4', '5', '6', '7', '8', '9'};
  uint8_t zeros[96] = {0};
  uint32_t crc = UINT32_C(0xa5a5a5a5);

  CHECK(oai_memprof_container_v1_crc32c(NULL, 0, &crc) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(crc == UINT32_C(0x00000000));
  CHECK(oai_memprof_container_v1_crc32c(digits, sizeof(digits), &crc) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(crc == UINT32_C(0xe3069283));
  CHECK(oai_memprof_container_v1_crc32c(zeros, sizeof(zeros), &crc) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(crc == UINT32_C(0x51f204ab));
  crc = UINT32_C(0x11223344);
  CHECK(oai_memprof_container_v1_crc32c(NULL, 1, &crc) == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(crc == UINT32_C(0x11223344));
  CHECK(oai_memprof_container_v1_crc32c(digits, sizeof(digits), NULL) == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  return true;
}

static bool test_sha256(void)
{
  static const uint8_t empty_digest[32] = {
      0xe3, 0xb0, 0xc4, 0x42, 0x98, 0xfc, 0x1c, 0x14, 0x9a, 0xfb, 0xf4, 0xc8, 0x99, 0x6f, 0xb9, 0x24,
      0x27, 0xae, 0x41, 0xe4, 0x64, 0x9b, 0x93, 0x4c, 0xa4, 0x95, 0x99, 0x1b, 0x78, 0x52, 0xb8, 0x55,
  };
  static const uint8_t abc[] = {'a', 'b', 'c'};
  static const uint8_t abc_digest[32] = {
      0xba, 0x78, 0x16, 0xbf, 0x8f, 0x01, 0xcf, 0xea, 0x41, 0x41, 0x40, 0xde, 0x5d, 0xae, 0x22, 0x23,
      0xb0, 0x03, 0x61, 0xa3, 0x96, 0x17, 0x7a, 0x9c, 0xb4, 0x10, 0xff, 0x61, 0xf2, 0x00, 0x15, 0xad,
  };
  uint8_t digest[32];
  memset(digest, 0xa5, sizeof(digest));
  CHECK(oai_memprof_container_v1_sha256(NULL, 0, digest) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(digest, empty_digest, sizeof(digest)) == 0);
  CHECK(oai_memprof_container_v1_sha256(abc, sizeof(abc), digest) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(digest, abc_digest, sizeof(digest)) == 0);
  memset(digest, 0xa5, sizeof(digest));
  CHECK(oai_memprof_container_v1_sha256(NULL, 1, digest) == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(digest, sizeof(digest), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_sha256(abc, sizeof(abc), NULL) == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  return true;
}

static bool test_opening_header_literal(void)
{
  oai_memprof_container_v1_opening_header_t decoded;
  uint8_t encoded[OAI_MEMPROF_CONTAINER_V1_OPENING_HEADER_SIZE];

  CHECK(oai_memprof_container_v1_opening_header_decode(&decoded, literal_opening_header, sizeof(literal_opening_header))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(decoded.page_size_bytes == UINT32_C(4096));
  CHECK(decoded.process_generation == UINT64_C(0x0102030405060708));
  CHECK(decoded.counter_frequency_numerator == UINT64_C(2400000000));
  CHECK(decoded.start_counter == UINT64_C(0x1122334455667788));
  CHECK(decoded.pid == UINT32_C(12345));
  CHECK(decoded.configured_thread_capacity == UINT32_C(256));
  CHECK(decoded.source_object_length == UINT16_C(20));

  memset(encoded, 0xa5, sizeof(encoded));
  CHECK(oai_memprof_container_v1_opening_header_encode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_opening_header, sizeof(encoded)) == 0);

  uint8_t bad_crc[sizeof(literal_opening_header)];
  memcpy(bad_crc, literal_opening_header, sizeof(bad_crc));
  bad_crc[OAI_MEMPROF_CONTAINER_V1_OPENING_PAGE_SIZE_BYTES_OFFSET] ^= UINT8_C(1);
  oai_memprof_container_v1_opening_header_t unchanged;
  memset(&unchanged, 0x5a, sizeof(unchanged));
  oai_memprof_container_v1_opening_header_t snapshot = unchanged;
  CHECK(oai_memprof_container_v1_opening_header_decode(&unchanged, bad_crc, sizeof(bad_crc))
        == OAI_MEMPROF_CONTAINER_V1_BAD_CHECKSUM);
  CHECK(memcmp(&unchanged, &snapshot, sizeof(unchanged)) == 0);

  decoded.page_size_bytes = UINT32_C(3);
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_opening_header_encode(&decoded, encoded, sizeof(encoded))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_VALUE);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));
  return true;
}

static bool test_chunk_literal(void)
{
  oai_memprof_container_v1_chunk_header_t decoded = {0};
  uint8_t encoded[OAI_MEMPROF_CONTAINER_V1_CHUNK_HEADER_SIZE];

  CHECK(oai_memprof_container_v1_chunk_header_decode(&decoded,
                                                     literal_chunk_header,
                                                     sizeof(literal_chunk_header),
                                                     literal_event_record,
                                                     sizeof(literal_event_record))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(decoded.writer_chunk_sequence == 0);
  CHECK(decoded.record_count == UINT32_C(1));
  memset(encoded, 0xa5, sizeof(encoded));
  CHECK(oai_memprof_container_v1_chunk_header_encode(&decoded,
                                                     literal_event_record,
                                                     sizeof(literal_event_record),
                                                     encoded,
                                                     sizeof(encoded))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_chunk_header, sizeof(encoded)) == 0);

  uint8_t bad_payload[sizeof(literal_event_record)];
  memcpy(bad_payload, literal_event_record, sizeof(bad_payload));
  bad_payload[0] ^= UINT8_C(1);
  const oai_memprof_container_v1_chunk_header_t sentinel = {.writer_chunk_sequence = UINT64_MAX, .record_count = UINT32_MAX};
  decoded = sentinel;
  CHECK(oai_memprof_container_v1_chunk_header_decode(&decoded,
                                                     literal_chunk_header,
                                                     sizeof(literal_chunk_header),
                                                     bad_payload,
                                                     sizeof(bad_payload))
        == OAI_MEMPROF_CONTAINER_V1_BAD_CHECKSUM);
  CHECK(decoded.writer_chunk_sequence == sentinel.writer_chunk_sequence && decoded.record_count == sentinel.record_count);

  memset(encoded, 0x5a, sizeof(encoded));
  decoded = (oai_memprof_container_v1_chunk_header_t){.writer_chunk_sequence = 0, .record_count = 1};
  CHECK(oai_memprof_container_v1_chunk_header_encode(&decoded,
                                                     literal_event_record,
                                                     sizeof(literal_event_record) - 1,
                                                     encoded,
                                                     sizeof(encoded))
        == OAI_MEMPROF_CONTAINER_V1_PAYLOAD_SIZE_MISMATCH);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));
  return true;
}

static bool test_trailer_literal(void)
{
  oai_memprof_container_v1_trailer_header_t decoded;
  uint8_t encoded[OAI_MEMPROF_CONTAINER_V1_TRAILER_HEADER_SIZE];

  CHECK(oai_memprof_container_v1_trailer_header_decode(&decoded, literal_trailer_header, sizeof(literal_trailer_header))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(decoded.trailer_body_bytes == UINT64_C(384));
  CHECK(decoded.lifecycle_state == OAI_MEMPROF_CONTAINER_V1_LIFECYCLE_INCOMPLETE);
  CHECK(decoded.payload_writer_state == OAI_MEMPROF_CONTAINER_V1_WRITER_PAYLOAD_CLOSED_VERIFIED);
  CHECK(decoded.finalization_stage == OAI_MEMPROF_CONTAINER_V1_FINALIZATION_ACTIVE_ONLY);
  CHECK(decoded.terminal_flags == UINT64_C(0x181));
  CHECK(decoded.object_entry_count == UINT32_C(2));
  CHECK(decoded.terminal_reason_code == OAI_MEMPROF_CONTAINER_V1_REASON_OPERATOR_CANCELLED);
  CHECK(oai_memprof_container_v1_trailer_header_encode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_trailer_header, sizeof(encoded)) == 0);

  uint8_t bad_reserved[sizeof(literal_trailer_header)];
  memcpy(bad_reserved, literal_trailer_header, sizeof(bad_reserved));
  bad_reserved[OAI_MEMPROF_CONTAINER_V1_TRAILER_RESERVED_ZERO_0_OFFSET] = UINT8_C(1);
  memset(&decoded, 0x5a, sizeof(decoded));
  oai_memprof_container_v1_trailer_header_t snapshot = decoded;
  CHECK(oai_memprof_container_v1_trailer_header_decode(&decoded, bad_reserved, sizeof(bad_reserved))
        == OAI_MEMPROF_CONTAINER_V1_NONZERO_RESERVED);
  CHECK(memcmp(&decoded, &snapshot, sizeof(decoded)) == 0);

  CHECK(oai_memprof_container_v1_trailer_header_decode(&decoded, literal_trailer_header, sizeof(literal_trailer_header))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  decoded.lifecycle_state = OAI_MEMPROF_CONTAINER_V1_LIFECYCLE_COMPLETE;
  decoded.finalization_stage = OAI_MEMPROF_CONTAINER_V1_FINALIZATION_PRE_SYNC_TERMINAL_MATERIAL_FROZEN;
  decoded.terminal_flags = OAI_MEMPROF_CONTAINER_V1_COMPLETE_REQUIRED_FLAGS;
  decoded.terminal_reason_code = OAI_MEMPROF_CONTAINER_V1_REASON_NONE;
  decoded.cutoff_before_counter = decoded.active_start_counter;
  decoded.cutoff_after_counter = decoded.active_start_counter;
  decoded.quiescence_complete_counter = decoded.active_start_counter;
  CHECK(oai_memprof_container_v1_trailer_header_encode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_CONTAINER_V1_OK);

  uint8_t process_lifetime_complete[sizeof(encoded)];
  memcpy(process_lifetime_complete, encoded, sizeof(process_lifetime_complete));
  process_lifetime_complete[OAI_MEMPROF_CONTAINER_V1_TRAILER_SCOPE_KIND_OFFSET] = OAI_MEMPROF_CONTAINER_V1_SCOPE_PROCESS_LIFETIME;
  process_lifetime_complete[OAI_MEMPROF_CONTAINER_V1_TRAILER_SCOPE_KIND_OFFSET + 1] = UINT8_C(0);
  memset(&decoded, 0x5a, sizeof(decoded));
  snapshot = decoded;
  CHECK(oai_memprof_container_v1_trailer_header_decode(&decoded, process_lifetime_complete, sizeof(process_lifetime_complete))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_RELATION);
  CHECK(memcmp(&decoded, &snapshot, sizeof(decoded)) == 0);

  CHECK(oai_memprof_container_v1_trailer_header_decode(&decoded, literal_trailer_header, sizeof(literal_trailer_header))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  decoded.lifecycle_state = OAI_MEMPROF_CONTAINER_V1_LIFECYCLE_COMPLETE;
  decoded.finalization_stage = OAI_MEMPROF_CONTAINER_V1_FINALIZATION_PRE_SYNC_TERMINAL_MATERIAL_FROZEN;
  decoded.terminal_flags = OAI_MEMPROF_CONTAINER_V1_COMPLETE_REQUIRED_FLAGS;
  decoded.terminal_reason_code = OAI_MEMPROF_CONTAINER_V1_REASON_NONE;
  decoded.cutoff_before_counter = decoded.active_start_counter;
  decoded.cutoff_after_counter = decoded.active_start_counter;
  decoded.quiescence_complete_counter = decoded.active_start_counter;
  decoded.scope_kind = OAI_MEMPROF_CONTAINER_V1_SCOPE_PROCESS_LIFETIME;
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_trailer_header_encode(&decoded, encoded, sizeof(encoded))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_RELATION);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));
  return true;
}

static bool test_table_entry_literals(void)
{
  uint8_t encoded[OAI_MEMPROF_CONTAINER_V1_OBJECT_ENTRY_SIZE];
  oai_memprof_container_v1_event_total_entry_t event_entry;
  oai_memprof_container_v1_diagnostic_total_entry_t diagnostic_entry;
  oai_memprof_container_v1_object_entry_t object_entry;

  CHECK(oai_memprof_container_v1_event_total_entry_decode(&event_entry, literal_event_total, sizeof(literal_event_total))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(event_entry.event_kind == UINT16_C(0x0102));
  CHECK(event_entry.api_id == UINT16_C(0x0304));
  CHECK(event_entry.record_count == UINT64_C(0x0102030405060708));
  CHECK(oai_memprof_container_v1_event_total_entry_encode(&event_entry, encoded, sizeof(literal_event_total))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_event_total, sizeof(literal_event_total)) == 0);

  event_entry.record_count = 0;
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_event_total_entry_encode(&event_entry, encoded, sizeof(literal_event_total))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_VALUE);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));
  uint8_t bad_event_total[sizeof(literal_event_total)];
  memcpy(bad_event_total, literal_event_total, sizeof(bad_event_total));
  bad_event_total[OAI_MEMPROF_CONTAINER_V1_EVENT_TOTAL_RESERVED_ZERO_0_OFFSET] = UINT8_C(1);
  memset(&event_entry, 0x5a, sizeof(event_entry));
  oai_memprof_container_v1_event_total_entry_t event_snapshot = event_entry;
  CHECK(oai_memprof_container_v1_event_total_entry_decode(&event_entry, bad_event_total, sizeof(bad_event_total))
        == OAI_MEMPROF_CONTAINER_V1_NONZERO_RESERVED);
  CHECK(memcmp(&event_entry, &event_snapshot, sizeof(event_entry)) == 0);

  CHECK(oai_memprof_container_v1_diagnostic_total_entry_decode(&diagnostic_entry,
                                                               literal_diagnostic_total,
                                                               sizeof(literal_diagnostic_total))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(diagnostic_entry.reason_id == UINT16_C(1));
  CHECK(diagnostic_entry.class_flags == UINT16_C(3));
  CHECK(diagnostic_entry.summary_flags == UINT32_C(1));
  CHECK(diagnostic_entry.saturating_total == UINT64_MAX);
  CHECK(diagnostic_entry.nonzero_counter_instances == UINT32_C(2));
  CHECK(diagnostic_entry.saturated_counter_instances == UINT32_C(1));
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_encode(&diagnostic_entry, encoded, sizeof(literal_diagnostic_total))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_diagnostic_total, sizeof(literal_diagnostic_total)) == 0);

  diagnostic_entry.saturated_counter_instances = diagnostic_entry.nonzero_counter_instances + UINT32_C(1);
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_encode(&diagnostic_entry, encoded, sizeof(literal_diagnostic_total))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_RELATION);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));

  diagnostic_entry.saturated_counter_instances = UINT32_C(1);
  diagnostic_entry.summary_flags = UINT32_C(0);
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_encode(&diagnostic_entry, encoded, sizeof(literal_diagnostic_total))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_RELATION);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));

  uint8_t bad_diagnostic_total[sizeof(literal_diagnostic_total)];
  memcpy(bad_diagnostic_total, literal_diagnostic_total, sizeof(bad_diagnostic_total));
  bad_diagnostic_total[OAI_MEMPROF_CONTAINER_V1_DIAGNOSTIC_TOTAL_RESERVED_ZERO_OFFSET] = UINT8_C(1);
  memset(&diagnostic_entry, 0x5a, sizeof(diagnostic_entry));
  oai_memprof_container_v1_diagnostic_total_entry_t diagnostic_snapshot = diagnostic_entry;
  CHECK(
      oai_memprof_container_v1_diagnostic_total_entry_decode(&diagnostic_entry, bad_diagnostic_total, sizeof(bad_diagnostic_total))
      == OAI_MEMPROF_CONTAINER_V1_NONZERO_RESERVED);
  CHECK(memcmp(&diagnostic_entry, &diagnostic_snapshot, sizeof(diagnostic_entry)) == 0);

  uint8_t missing_saturation_summary[sizeof(literal_diagnostic_total)];
  memcpy(missing_saturation_summary, literal_diagnostic_total, sizeof(missing_saturation_summary));
  memset(missing_saturation_summary + OAI_MEMPROF_CONTAINER_V1_DIAGNOSTIC_TOTAL_SUMMARY_FLAGS_OFFSET, 0, sizeof(uint32_t));
  memset(&diagnostic_entry, 0x5a, sizeof(diagnostic_entry));
  diagnostic_snapshot = diagnostic_entry;
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_decode(&diagnostic_entry,
                                                               missing_saturation_summary,
                                                               sizeof(missing_saturation_summary))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_RELATION);
  CHECK(memcmp(&diagnostic_entry, &diagnostic_snapshot, sizeof(diagnostic_entry)) == 0);

  CHECK(oai_memprof_container_v1_object_entry_decode(&object_entry, literal_object_entry, sizeof(literal_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(object_entry.object_kind == UINT16_C(1));
  CHECK(object_entry.format_id == UINT16_C(1));
  CHECK(object_entry.object_flags == UINT32_C(5));
  CHECK(object_entry.schema_revision == UINT32_C(1));
  CHECK(object_entry.entry_count == UINT64_C(7));
  CHECK(object_entry.byte_count == UINT64_C(32));
  CHECK(oai_memprof_container_v1_object_entry_encode(&object_entry, encoded, sizeof(literal_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_object_entry, sizeof(literal_object_entry)) == 0);

  object_entry.object_kind = UINT16_C(2);
  object_entry.entry_count = UINT64_C(12);
  CHECK(oai_memprof_container_v1_object_entry_encode(&object_entry, encoded, sizeof(literal_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_OK);
  uint8_t api_object_entry_wire[sizeof(literal_object_entry)];
  memcpy(api_object_entry_wire, encoded, sizeof(api_object_entry_wire));
  object_entry.entry_count = UINT64_C(4);
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_object_entry_encode(&object_entry, encoded, sizeof(literal_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_VALUE);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));
  memset(api_object_entry_wire + OAI_MEMPROF_CONTAINER_V1_OBJECT_ENTRY_COUNT_OFFSET, 0, sizeof(uint64_t));
  api_object_entry_wire[OAI_MEMPROF_CONTAINER_V1_OBJECT_ENTRY_COUNT_OFFSET] = UINT8_C(4);
  memset(&object_entry, 0x5a, sizeof(object_entry));
  oai_memprof_container_v1_object_entry_t api_object_snapshot = object_entry;
  CHECK(oai_memprof_container_v1_object_entry_decode(&object_entry, api_object_entry_wire, sizeof(api_object_entry_wire))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_VALUE);
  CHECK(memcmp(&object_entry, &api_object_snapshot, sizeof(object_entry)) == 0);
  CHECK(oai_memprof_container_v1_object_entry_decode(&object_entry, literal_object_entry, sizeof(literal_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_OK);

  object_entry.object_flags = 0;
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_object_entry_encode(&object_entry, encoded, sizeof(literal_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_INVALID_VALUE);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));

  uint8_t bad_object_entry[sizeof(literal_object_entry)];
  memcpy(bad_object_entry, literal_object_entry, sizeof(bad_object_entry));
  bad_object_entry[OAI_MEMPROF_CONTAINER_V1_OBJECT_RESERVED_ZERO_OFFSET] = UINT8_C(1);
  memset(&object_entry, 0x5a, sizeof(object_entry));
  oai_memprof_container_v1_object_entry_t object_snapshot = object_entry;
  CHECK(oai_memprof_container_v1_object_entry_decode(&object_entry, bad_object_entry, sizeof(bad_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_NONZERO_RESERVED);
  CHECK(memcmp(&object_entry, &object_snapshot, sizeof(object_entry)) == 0);
  return true;
}

static bool test_footer_literal(void)
{
  oai_memprof_container_v1_footer_t decoded;
  uint8_t encoded[OAI_MEMPROF_CONTAINER_V1_FOOTER_SIZE];

  CHECK(oai_memprof_container_v1_footer_decode(&decoded, literal_footer, sizeof(literal_footer)) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(decoded.trailer_offset == UINT64_C(512));
  CHECK(decoded.trailer_body_bytes == UINT64_C(384));
  CHECK(decoded.stream_bytes == UINT64_C(1152));
  CHECK(decoded.prefix_bytes == UINT64_C(512));
  CHECK(decoded.chunk_count == 0 && decoded.record_count == 0);
  CHECK(oai_memprof_container_v1_footer_encode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_footer, sizeof(literal_footer)) == 0);

  memset(decoded.footer_sha256, 0, sizeof(decoded.footer_sha256));
  CHECK(oai_memprof_container_v1_footer_encode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_CONTAINER_V1_OK);
  CHECK(memcmp(encoded, literal_footer, sizeof(literal_footer)) == 0);

  decoded.footer_sha256[0] = UINT8_C(1);
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_footer_encode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_CONTAINER_V1_BAD_CHECKSUM);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));

  uint8_t bad_footer_hash[sizeof(literal_footer)];
  memcpy(bad_footer_hash, literal_footer, sizeof(bad_footer_hash));
  bad_footer_hash[OAI_MEMPROF_CONTAINER_V1_FOOTER_FOOTER_SHA256_OFFSET] ^= UINT8_C(1);
  memset(&decoded, 0x5a, sizeof(decoded));
  oai_memprof_container_v1_footer_t snapshot = decoded;
  CHECK(oai_memprof_container_v1_footer_decode(&decoded, bad_footer_hash, sizeof(bad_footer_hash))
        == OAI_MEMPROF_CONTAINER_V1_BAD_CHECKSUM);
  CHECK(memcmp(&decoded, &snapshot, sizeof(decoded)) == 0);

  uint8_t bad_footer_version[sizeof(literal_footer)];
  memcpy(bad_footer_version, literal_footer, sizeof(bad_footer_version));
  bad_footer_version[OAI_MEMPROF_CONTAINER_V1_FOOTER_SCHEMA_MINOR_OFFSET] = UINT8_C(1);
  CHECK(oai_memprof_container_v1_footer_decode(&decoded, bad_footer_version, sizeof(bad_footer_version))
        == OAI_MEMPROF_CONTAINER_V1_BAD_CHECKSUM);
  CHECK(memcmp(&decoded, &snapshot, sizeof(decoded)) == 0);

  CHECK(oai_memprof_container_v1_footer_decode(&decoded, literal_footer, sizeof(literal_footer)) == OAI_MEMPROF_CONTAINER_V1_OK);
  decoded.stream_bytes++;
  memset(encoded, 0x5a, sizeof(encoded));
  CHECK(oai_memprof_container_v1_footer_encode(&decoded, encoded, sizeof(encoded)) == OAI_MEMPROF_CONTAINER_V1_INVALID_RELATION);
  CHECK(bytes_are_value(encoded, sizeof(encoded), UINT8_C(0x5a)));
  return true;
}

static bool test_exact_size_and_null_rejection(void)
{
  oai_memprof_container_v1_opening_header_t opening;
  oai_memprof_container_v1_chunk_header_t chunk;
  oai_memprof_container_v1_trailer_header_t trailer;
  oai_memprof_container_v1_event_total_entry_t event_entry;
  oai_memprof_container_v1_diagnostic_total_entry_t diagnostic_entry;
  oai_memprof_container_v1_object_entry_t object_entry;
  oai_memprof_container_v1_footer_t footer;
  uint8_t output[OAI_MEMPROF_CONTAINER_V1_OPENING_HEADER_SIZE];

  memset(&opening, 0x5a, sizeof(opening));
  const oai_memprof_container_v1_opening_header_t opening_snapshot = opening;
  memset(output, 0xa5, sizeof(output));
  CHECK(oai_memprof_container_v1_opening_header_decode(NULL, literal_opening_header, sizeof(literal_opening_header))
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(oai_memprof_container_v1_opening_header_decode(&opening, literal_opening_header, sizeof(literal_opening_header) - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(memcmp(&opening, &opening_snapshot, sizeof(opening)) == 0);
  CHECK(oai_memprof_container_v1_opening_header_encode(NULL, output, sizeof(output)) == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_opening_header_encode(&opening, output, OAI_MEMPROF_CONTAINER_V1_OPENING_HEADER_SIZE - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));

  memset(&chunk, 0x5a, sizeof(chunk));
  const oai_memprof_container_v1_chunk_header_t chunk_snapshot = chunk;
  CHECK(oai_memprof_container_v1_chunk_header_decode(NULL,
                                                     literal_chunk_header,
                                                     sizeof(literal_chunk_header),
                                                     literal_event_record,
                                                     sizeof(literal_event_record))
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(oai_memprof_container_v1_chunk_header_decode(&chunk,
                                                     literal_chunk_header,
                                                     sizeof(literal_chunk_header) - 1,
                                                     literal_event_record,
                                                     sizeof(literal_event_record))
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(memcmp(&chunk, &chunk_snapshot, sizeof(chunk)) == 0);
  CHECK(oai_memprof_container_v1_chunk_header_encode(NULL,
                                                     literal_event_record,
                                                     sizeof(literal_event_record),
                                                     output,
                                                     OAI_MEMPROF_CONTAINER_V1_CHUNK_HEADER_SIZE)
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_chunk_header_encode(&chunk,
                                                     literal_event_record,
                                                     sizeof(literal_event_record),
                                                     output,
                                                     OAI_MEMPROF_CONTAINER_V1_CHUNK_HEADER_SIZE - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));

  memset(&trailer, 0x5a, sizeof(trailer));
  const oai_memprof_container_v1_trailer_header_t trailer_snapshot = trailer;
  CHECK(oai_memprof_container_v1_trailer_header_decode(NULL, literal_trailer_header, sizeof(literal_trailer_header))
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(oai_memprof_container_v1_trailer_header_decode(&trailer, literal_trailer_header, sizeof(literal_trailer_header) - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(memcmp(&trailer, &trailer_snapshot, sizeof(trailer)) == 0);
  CHECK(oai_memprof_container_v1_trailer_header_encode(NULL, output, OAI_MEMPROF_CONTAINER_V1_TRAILER_HEADER_SIZE)
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_trailer_header_encode(&trailer, output, OAI_MEMPROF_CONTAINER_V1_TRAILER_HEADER_SIZE - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));

  memset(&event_entry, 0x5a, sizeof(event_entry));
  const oai_memprof_container_v1_event_total_entry_t event_snapshot = event_entry;
  CHECK(oai_memprof_container_v1_event_total_entry_decode(NULL, literal_event_total, sizeof(literal_event_total))
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(oai_memprof_container_v1_event_total_entry_decode(&event_entry, literal_event_total, sizeof(literal_event_total) - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(memcmp(&event_entry, &event_snapshot, sizeof(event_entry)) == 0);
  CHECK(oai_memprof_container_v1_event_total_entry_encode(NULL, output, OAI_MEMPROF_CONTAINER_V1_EVENT_TOTAL_ENTRY_SIZE)
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_event_total_entry_encode(&event_entry, output, OAI_MEMPROF_CONTAINER_V1_EVENT_TOTAL_ENTRY_SIZE - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));

  memset(&diagnostic_entry, 0x5a, sizeof(diagnostic_entry));
  const oai_memprof_container_v1_diagnostic_total_entry_t diagnostic_snapshot = diagnostic_entry;
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_decode(NULL, literal_diagnostic_total, sizeof(literal_diagnostic_total))
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_decode(&diagnostic_entry,
                                                               literal_diagnostic_total,
                                                               sizeof(literal_diagnostic_total) - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(memcmp(&diagnostic_entry, &diagnostic_snapshot, sizeof(diagnostic_entry)) == 0);
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_encode(NULL, output, OAI_MEMPROF_CONTAINER_V1_DIAGNOSTIC_TOTAL_ENTRY_SIZE)
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_diagnostic_total_entry_encode(&diagnostic_entry,
                                                               output,
                                                               OAI_MEMPROF_CONTAINER_V1_DIAGNOSTIC_TOTAL_ENTRY_SIZE - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));

  memset(&object_entry, 0x5a, sizeof(object_entry));
  const oai_memprof_container_v1_object_entry_t object_snapshot = object_entry;
  CHECK(oai_memprof_container_v1_object_entry_decode(NULL, literal_object_entry, sizeof(literal_object_entry))
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(oai_memprof_container_v1_object_entry_decode(&object_entry, literal_object_entry, sizeof(literal_object_entry) - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(memcmp(&object_entry, &object_snapshot, sizeof(object_entry)) == 0);
  CHECK(oai_memprof_container_v1_object_entry_encode(NULL, output, OAI_MEMPROF_CONTAINER_V1_OBJECT_ENTRY_SIZE)
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_object_entry_encode(&object_entry, output, OAI_MEMPROF_CONTAINER_V1_OBJECT_ENTRY_SIZE - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));

  memset(&footer, 0x5a, sizeof(footer));
  const oai_memprof_container_v1_footer_t footer_snapshot = footer;
  CHECK(oai_memprof_container_v1_footer_decode(NULL, literal_footer, sizeof(literal_footer))
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(oai_memprof_container_v1_footer_decode(&footer, literal_footer, sizeof(literal_footer) - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(memcmp(&footer, &footer_snapshot, sizeof(footer)) == 0);
  CHECK(oai_memprof_container_v1_footer_encode(NULL, output, OAI_MEMPROF_CONTAINER_V1_FOOTER_SIZE)
        == OAI_MEMPROF_CONTAINER_V1_NULL_ARGUMENT);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  CHECK(oai_memprof_container_v1_footer_encode(&footer, output, OAI_MEMPROF_CONTAINER_V1_FOOTER_SIZE - 1)
        == OAI_MEMPROF_CONTAINER_V1_WRONG_SIZE);
  CHECK(bytes_are_value(output, sizeof(output), UINT8_C(0xa5)));
  return true;
}

int main(void)
{
  if (!test_crc32c() || !test_sha256() || !test_opening_header_literal() || !test_chunk_literal() || !test_trailer_literal()
      || !test_table_entry_literals() || !test_footer_literal() || !test_exact_size_and_null_rejection())
    return EXIT_FAILURE;

  puts("schema-v1 container wire tests passed");
  return EXIT_SUCCESS;
}
