services:
    oai-gnb:
        image: ${REGISTRY:-oaisoftwarealliance}/oai-gnb-fhi72-t2:${TAG:-develop}
        cap_add:
            - IPC_LOCK
            - SYS_NICE
        cap_drop:
            - ALL
        container_name: oai-gnb
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --thread-pool 13,14,15,16,17,18,19,20 --loader.ldpc.shlibversion _t2 --nrLDPC_coding_t2.dpdk_dev 01:00.0 --nrLDPC_coding_t2.dpdk_core_list 22,23
        devices:
            - /dev/vfio:/dev/vfio/
        volumes:
            - ../../conf_files/gnb.sa.band77.273prb.fhi72.4x4-4L-vvdn.conf:/opt/oai-gnb/etc/gnb.conf
            - /dev/hugepages:/dev/hugepages
        # Please change these values based on your system
        cpuset: "7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23"
        networks:
            oai-net:
                ipv4_address: 172.21.10.20
        healthcheck:
           test: /bin/bash -c "/opt/oai-gnb/bin/check-prach-io.sh"
           start_period: 15s
           start_interval: 500ms
           interval: 5s
           timeout: 5s
           retries: 10

networks:
    oai-net:
        driver: macvlan
        name: oai-net
        ipam:
            config:
                - subnet: "172.21.8.0/22"
                  ip_range: "172.21.10.20/32"
                  gateway: "172.21.11.254"
        driver_opts:
            com.docker.network.bridge.name: "oai-net"
            parent: bond0
