/*
 *****************************************************************
 *
 * Module  : SIDL - structures definitions
 *
 * Purpose : THIS FILE IS AUTOMATICALLY GENERATED !
 *
 *****************************************************************
 *
 *  Copyright (c) 2014-2021 SEQUANS Communications.
 *  All rights reserved.
 *
 *  This is confidential and proprietary source code of SEQUANS
 *  Communications. The use of the present source code and all
 *  its derived forms is exclusively governed by the restricted
 *  terms and conditions set forth in the SEQUANS
 *  Communications' EARLY ADOPTER AGREEMENT and/or LICENCE
 *  AGREEMENT. The present source code and all its derived
 *  forms can ONLY and EXCLUSIVELY be used with SEQUANS
 *  Communications' products. The distribution/sale of the
 *  present source code and all its derived forms is EXCLUSIVELY
 *  RESERVED to regular LICENCE holder and otherwise STRICTLY
 *  PROHIBITED.
 *
 *****************************************************************
 */

#pragma once

#include "SidlCompiler.h"
#include "SidlASN1.h"
#include "SidlASN1Base.h"
#include "SidlBase.h"
#include "SidlCommon.h"
#include "SidlCommonBase.h"
#include "SidlParts.h"
#include "SidlVals.h"
#include "TtcnCommon.h"
#include "SidlCommon_BcchConfig.h"
#include "SidlCommon_Bcch_BRConfig.h"
#include "SidlCommon_CcchDcchDtchConfig.h"
#include "SidlCommon_InitialCellPower.h"
#include "SidlCommon_PhysicalLayerConfigDL.h"
#include "SidlCommon_PhysicalLayerConfigUL.h"
#include "SidlCommon_RachProcedureConfig.h"
#include "SidlCommon_SciSchedulingConfig.h"
#include "SidlCommon_ServingCellConfig.h"
#include "SidlCommon_StaticCellInfo.h"
#include "SidlCommon_CellConfigRequest.h"

SIDL_BEGIN_C_INTERFACE

typedef Null_Type EUTRA_VngConfigConfirm_Type;

typedef int32_t NocLevel_Type;

struct EUTRA_VngConfigInfo_Type {
	Dl_Bandwidth_Type Bandwidth;
	NocLevel_Type NocLevel;
};

enum EUTRA_VngConfigRequest_Type_Sel {
	EUTRA_VngConfigRequest_Type_UNBOUND_VALUE = 0,
	EUTRA_VngConfigRequest_Type_Configure = 1,
	EUTRA_VngConfigRequest_Type_Activate = 2,
	EUTRA_VngConfigRequest_Type_Deactivate = 3,
};

union EUTRA_VngConfigRequest_Type_Value {
	struct EUTRA_VngConfigInfo_Type Configure;
	Null_Type Activate;
	Null_Type Deactivate;
};

struct EUTRA_VngConfigRequest_Type {
	enum EUTRA_VngConfigRequest_Type_Sel d;
	union EUTRA_VngConfigRequest_Type_Value v;
};

struct EUTRA_VNG_CTRL_REQ {
	struct ReqAspCommonPart_Type Common;
	struct EUTRA_VngConfigRequest_Type Request;
};

struct EUTRA_VNG_CTRL_CNF {
	struct CnfAspCommonPart_Type Common;
	EUTRA_VngConfigConfirm_Type Confirm;
};

SIDL_END_C_INTERFACE
