/*
 *****************************************************************
 *
 * Module  : SIDL - structures definitions
 *
 * Purpose : THIS FILE IS AUTOMATICALLY GENERATED !
 *
 *****************************************************************
 *
 *  Copyright (c) 2014-2021 SEQUANS Communications.
 *  All rights reserved.
 *
 *  This is confidential and proprietary source code of SEQUANS
 *  Communications. The use of the present source code and all
 *  its derived forms is exclusively governed by the restricted
 *  terms and conditions set forth in the SEQUANS
 *  Communications' EARLY ADOPTER AGREEMENT and/or LICENCE
 *  AGREEMENT. The present source code and all its derived
 *  forms can ONLY and EXCLUSIVELY be used with SEQUANS
 *  Communications' products. The distribution/sale of the
 *  present source code and all its derived forms is EXCLUSIVELY
 *  RESERVED to regular LICENCE holder and otherwise STRICTLY
 *  PROHIBITED.
 *
 *****************************************************************
 */

#pragma once

#include "SidlCompiler.h"
#include "SidlASN1.h"
#include "SidlASN1Base.h"
#include "SidlBase.h"
#include "SidlCommon.h"
#include "SidlCommonBase.h"

SIDL_BEGIN_C_INTERFACE

typedef int32_t DRB_Identity;

enum NR_RadioBearerId_Type_Sel {
	NR_RadioBearerId_Type_UNBOUND_VALUE = 0,
	NR_RadioBearerId_Type_Srb = 1,
	NR_RadioBearerId_Type_Drb = 2,
};

union NR_RadioBearerId_Type_Value {
	SRB_Identity_Type Srb;
	DRB_Identity Drb;
};

struct NR_RadioBearerId_Type {
	enum NR_RadioBearerId_Type_Sel d;
	union NR_RadioBearerId_Type_Value v;
};

enum NR_RoutingInfo_Type_Sel {
	NR_RoutingInfo_Type_UNBOUND_VALUE = 0,
	NR_RoutingInfo_Type_None = 1,
	NR_RoutingInfo_Type_RadioBearerId = 2,
	NR_RoutingInfo_Type_QosFlow = 3,
};

union NR_RoutingInfo_Type_Value {
	Null_Type None;
	struct NR_RadioBearerId_Type RadioBearerId;
	struct QosFlow_Identification_Type QosFlow;
};

struct NR_RoutingInfo_Type {
	enum NR_RoutingInfo_Type_Sel d;
	union NR_RoutingInfo_Type_Value v;
};

typedef Null_Type NR_RoutingInfoSUL_Type;

struct NR_RoutingInfoSUL_Type_RoutingInfoSUL_Optional {
	bool d;
	NR_RoutingInfoSUL_Type v;
};

struct NR_IndAspCommonPart_Type {
	NR_CellId_Type CellId;
	struct NR_RoutingInfo_Type RoutingInfo;
	struct NR_RoutingInfoSUL_Type_RoutingInfoSUL_Optional RoutingInfoSUL;
	struct RlcBearerRouting_Type RlcBearerRouting;
	struct TimingInfo_Type TimingInfo;
	struct IndicationStatus_Type Status;
};

struct NR_ReqAspCommonPart_Type {
	NR_CellId_Type CellId;
	struct NR_RoutingInfo_Type RoutingInfo;
	struct RlcBearerRouting_Type RlcBearerRouting;
	struct TimingInfo_Type TimingInfo;
	struct ReqAspControlInfo_Type ControlInfo;
};

SIDL_END_C_INTERFACE
