/*
 *****************************************************************
 *
 * Module  : SIDL - structures definitions
 *
 * Purpose : THIS FILE IS AUTOMATICALLY GENERATED !
 *
 *****************************************************************
 *
 *  Copyright (c) 2014-2021 SEQUANS Communications.
 *  All rights reserved.
 *
 *  This is confidential and proprietary source code of SEQUANS
 *  Communications. The use of the present source code and all
 *  its derived forms is exclusively governed by the restricted
 *  terms and conditions set forth in the SEQUANS
 *  Communications' EARLY ADOPTER AGREEMENT and/or LICENCE
 *  AGREEMENT. The present source code and all its derived
 *  forms can ONLY and EXCLUSIVELY be used with SEQUANS
 *  Communications' products. The distribution/sale of the
 *  present source code and all its derived forms is EXCLUSIVELY
 *  RESERVED to regular LICENCE holder and otherwise STRICTLY
 *  PROHIBITED.
 *
 *****************************************************************
 */

#pragma once

#include "SidlCompiler.h"

SIDL_BEGIN_C_INTERFACE

typedef uint8_t OCTET_STRING_ELEMENT;

typedef uint8_t BIT_STRING_ELEMENT;

struct OCTET_STRING_ELEMENT_OCTET_STRING_Dynamic {
	size_t d;
	OCTET_STRING_ELEMENT* v;
};

typedef struct OCTET_STRING_ELEMENT_OCTET_STRING_Dynamic OCTET_STRING;

struct BIT_STRING_ELEMENT_BIT_STRING_Dynamic {
	size_t d;
	BIT_STRING_ELEMENT* v;
};

typedef struct BIT_STRING_ELEMENT_BIT_STRING_Dynamic BIT_STRING;

struct int32_t_PREGEN_RECORD_OF_INTEGER_Dynamic {
	size_t d;
	int32_t* v;
};

typedef struct int32_t_PREGEN_RECORD_OF_INTEGER_Dynamic PREGEN_RECORD_OF_INTEGER;

SIDL_END_C_INTERFACE
